### ISSUE TITLE
Powerpoint 

### ISSUE THREAD

**Issue by dzaremba90** [Microsoft/MCW-SAP-NetWeaver-on-Azure#1]
1. Many of the images do not meet the color contrast standards :
- Slide 10 - Graphic (light gray/medium gray) (blue/white)
- Slide 12 - Graphic (white/medium gray) (blue/white)
- Slide 13 - Graphic Fails AAA 
- Slide 18 - “Availability Set” graphic (green/white; blue/white)
- Slide 24 - “Benefits of MCP” graphic (blue/white)
- Slide 25 - Graphic (white/medium gray) (blue/white)
- Slide 33 - Graphic (Green/red)

2. None of the images have alt text provided.

**Comment by DawnmarieDesJardins** [comment]
Closing issue, Diana corrected PPT and reuploaded.
