### ISSUE TITLE
Health probes not found.

### ISSUE THREAD

**Issue by fasalzaman** [Microsoft/MCW-SAP-NetWeaver-on-Azure#16]
In Exercise 1 > Task 4 > Steps 18 :  lb00ProbePortxSCS health probe not found in s03-lb-ascs load balancer.
In Exercise 1 > Task 4 > Steps 20 :  lb00ProbePortDB health probe not found in s03-lb-db load balancer.

**Comment by DawnmarieDesJardins** [comment]
@mwasham @Jeff-Opsgility 
Please address in March test/fix.
Planned presentation scheduled for 4/5/19

**Comment by DawnmarieDesJardins** [comment]
Closing issue - addressed in merged PR #17
