### ISSUE TITLE
Parameters are not matching

### ISSUE THREAD

**Issue by Gvashi** [microsoft/MCW-SAP-NetWeaver-on-Azure#19]
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"InvalidRequestFormat\",\r\n \"message\": \"Cannot parse the request.\",\r\n \"details\": [\r\n {\r\n \"code\": \"InvalidJsonReferenceFormat\",\r\n \"message\": \"Reference Id /subscriptions/41ca5ed7-3e4f-4a30-b857-9cdad18ad91e/resourceGroups/ODL-sap-netweaver-79007-s03RG/providers/Microsoft.Network/virtualNetworks/s03-RG-vnet/subnests is not formatted correctly. The Id is expected to reference resources of type virtualNetworks/subnets. Path properties.ipConfigurations[0].properties.subnet.\"\r\n }\r\n ]\r\n }\r\n}"},{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"InvalidRequestFormat\",\r\n \"message\": \"Cannot parse the request.\",\r\n \"details\": [\r\n {\r\n \"code\": \"InvalidJsonReferenceFormat\",\r\n \"message\": \"Reference Id /subscriptions/41ca5ed7-3e4f-4a30-b857-9cdad18ad91e/resourceGroups/ODL-sap-netweaver-79007-s03RG/providers/Microsoft.Network/virtualNetworks/s03-RG-vnet/subnests is not formatted correctly. The Id is expected to reference resources of type virtualNetworks/subnets. Path properties.ipConfigurations[0].properties.subnet.\"\r\n }\r\n ]\r\n }\r\n}"},{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"InvalidRequestFormat\",\r\n \"message\": \"Cannot parse the request.\",\r\n \"details\": [\r\n {\r\n \"code\": \"InvalidJsonReferenceFormat\",\r\n \"message\": \"Reference Id /subscriptions/41ca5ed7-3e4f-4a30-b857-9cdad18ad91e/resourceGroups/ODL-sap-netweaver-79007-s03RG/providers/Microsoft.Network/virtualNetworks/s03-RG-vnet/subnests is not formatted correctly. The Id is expected to reference resources of type virtualNetworks/subnets. Path properties.ipConfigurations[0].properties.subnet.\"\r\n }\r\n ]\r\n }\r\n}"}]}

**Comment by DawnmarieDesJardins** [comment]
@polichtm 
Hi Marcin,  Please review and advise.

**Comment by polichtm** [comment]
as the error indicates, /subscriptions/41ca5ed7-3e4f-4a30-b857-9cdad18ad91e/resourceGroups/ODL-sap-netweaver-79007-s03RG/providers/Microsoft.Network/virtualNetworks/s03-RG-vnet/subnests is not formatted correctly. The Id is expected to reference resources of type virtualNetworks/subnets is invalid. 

To determine the reference ID, pls run:
$vnet = Get-AzVirtualNetwork -ResourceGroupName s03-RG -Name s03-RG-vnet
$subnet = Get-AzVirtualNetworkSubnetConfig -Name 'sapSubnet' -VirtualNetwork $vnet
$subnet.Id

the output should be in the format:

![image](https://user-images.githubusercontent.com/10284906/65559996-ecfa3b80-df0a-11e9-943e-1f42695c9135.png)

rgds
Marcin
