### ISSUE TITLE
Deployment failing of  "SAP NetWeaver application and database tier VMs " Exercise 1 task 5.

### ISSUE THREAD

**Issue by akn9050** [Microsoft/MCW-SAP-NetWeaver-on-Azure#9]
Custom script extension provisioning is failing for all the of application and database VMs in exercise 1 task 5 https://github.com/Microsoft/MCW-SAP-NetWeaver-on-Azure/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20SAP%20NetWeaver%20on%20Azure.md#task-4-deploy-sap-netweaver-application-and-database-tier-vms

Following are the error screenshots: 

![snag_2d73aeec](https://user-images.githubusercontent.com/27498287/47616633-a5461680-dae5-11e8-89cb-5c484cb7e4d3.png)

![snag_2d742d15](https://user-images.githubusercontent.com/27498287/47616639-b55df600-dae5-11e8-8197-6f40c35c6644.png)

![snag_2d74dd79](https://user-images.githubusercontent.com/27498287/47616650-d0c90100-dae5-11e8-977f-5a928d18991d.png)

Status in VM extension blade: Provisioning failed.
[
    {
        "code": "ComponentStatus/StdOut/succeeded",
        "level": "Info",
        "displayStatus": "Provisioning succeeded",
        "message": "Windows PowerShell \\nCopyright (C) 2016 Microsoft Corporation. All rights reserved.\\n"
    },
    {
        "code": "ComponentStatus/StdErr/succeeded",
        "level": "Info",
        "displayStatus": "Provisioning succeeded",
        "message": "The argument '.\\shared\\noop.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter."
    }
]

![snag_2d7816f9](https://user-images.githubusercontent.com/27498287/47616697-4fbe3980-dae6-11e8-8d6c-422ceaa1a52e.png)

**Comment by DawnmarieDesJardins** [comment]
Assigning to Michael to verify this addressed in the current test/fix.

**Comment by akn9050** [comment]
Any update on this?

**Comment by mwasham** [comment]
We just updated/tested the lab in the sept-2018-testfix branch and validated that the deployment worked. You may want to try it instead (it will be merged soon).

**Comment by akn9050** [comment]
Hi @mwasham, is it merged. Can I proceed with the lab.

**Comment by DawnmarieDesJardins** [comment]
Hi @akn9050 - Updates are complete, please continue with the lab.
